baseURL = "https://blog.vhxubo.com"
languageCode = "zh-CN"
title = "Vhxubo's blog"
theme = "maupassant"

summaryLength = 140
hasCJKLanguage = true
enableEmoji = true
[author]
  name = "Vhxubo"

[params]
  author = "Vhxubo"
  subtitle = "专注摸鱼、踩坑，热衷于学习并开发各种插件"
  keywords = "Vhxubo,AngUOI,Guimi,博客"
  description = "记录有用的知识"
  busuanzi = true
  localSearch = true

  [params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

  [params.utteranc]
    enable = true
    repo = "vhxubo/utterances-comment"
    issueTerm = "pathname"
    theme = "github-light"
    label = "blog"

  [params.duration]
    timeStamp = "1415721600"
    leftImage = "http://q.qlogo.cn/headimg_dl?dst_uin=2711402167&spec=640&img_type=jpg"
    rightImage = "http://q.qlogo.cn/headimg_dl?dst_uin=925122985&spec=640&img_type=jpg"
  
  [params.hint]
    readInfo = true
    lastmod = true

[markup]
  [markup.highlight]
    lineNos = true
    style = "github"
    
[menu]

  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4
