baseURL = "https://blog.vhxubo.com"
languageCode = "zh-CN"
title = "Vhxubo's blog"
theme = "maupassant"
googleAnalytics = "UA-163590153-1"

summaryLength = 140
hasCJKLanguage = true
enableEmoji = true

[author]
  name = "Vhxubo"

[params]
  author = "Vhxubo"
  subtitle = "专注摸鱼、踩坑，热衷于学习并开发各种插件"
  keywords = "Vhxubo,AngUOI,Guimi,博客,Hugo,工具"
  description = "记录有用的知识"
  busuanzi = true
  localSearch = true

  [params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

  [params.utteranc]
    enable = true
    repo = "vhxubo/utterances-comment"
    issueTerm = "pathname"
    theme = "github-light"
    label = "blog"
    
[markup]
  [markup.highlight]
    style = "github"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "tools"
    name = "工具"
    url = "/tools/"
    weight = 2

  [[menu.main]]
    identifier = "projects"
    name = "项目"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 4

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 5
