baseURL = "https://blog.zxbzn.com/"
languageCode = "zh-CN"
title = "AngUOI"
theme = "maupassant"
# 文章摘要长度默认70
summaryLength = 70
hasCJKLanguage = true
enableEmoji = true
[author]
  name = "Guimi"

[params]
  author = "Guimi"
  subtitle = "一个爱折腾，对编程充满好奇的渣渣"
  keywords = "AngUOI,Guimi"
  description = "记录一些无趣、有用的事情"
  busuanzi = true

  [params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

  [params.utteranc]
    enable = true
    repo = "anguoi/utterances-comment"
    issueTerm = "pathname"
    theme = "github-light"
    label = "blog"

  [params.duration]
    timeStamp = "1415721600"
    leftImage = "http://q.qlogo.cn/headimg_dl?dst_uin=2711402167&spec=640&img_type=jpg"
    rightImage = "http://q.qlogo.cn/headimg_dl?dst_uin=925122985&spec=640&img_type=jpg"
  
  [params.hint]
    readInfo = true
    lastmod = true

[menu]

  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4
