baseURL = "https://blog.zxbzn.com/"
languageCode = "zh-CN"
title = "AngUOI"
theme = "maupassant"
# 文章摘要长度默认70
summaryLength = 70
hasCJKLanguage = true
enableEmoji = true
[author]
  name = "Guimi"

[params]
  author = "Guimi"
  subtitle = "一个爱折腾，对编程充满好奇的渣渣"
  keywords = "AngUOI,Guimi"
  description = "记录一些无趣、有用的事情"

  customJS = ['duration.js']

  [params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

  [menu]

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4
